# Generated by Django 3.1.7 on 2021-10-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi_commander', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Relay 1', max_length=40)),
                ('description', models.CharField(default='', max_length=250)),
                ('raspberry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi_commander.raspberry')),
            ],
        ),
    ]
