# Generated by Django 3.1.7 on 2021-10-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_commander', '0002_relay'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='label',
            field=models.CharField(default='Switch 1', max_length=12),
        ),
    ]
