# Generated by Django 3.1.7 on 2021-11-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi_commander', '0005_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relay',
            name='description',
        ),
    ]
