# Generated by Django 3.1.7 on 2021-11-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_commander', '0006_remove_relay_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
