# Generated by Django 3.1.7 on 2021-11-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_commander', '0007_action_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='time_unit',
            field=models.CharField(choices=[('D', 'Days'), ('H', 'Hours'), ('M', 'Minutes'), ('S', 'Seconds')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='action',
            name='time_out',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
