# Generated by Django 3.1.7 on 2021-11-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_commander', '0008_auto_20211116_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
