# Generated by Django 3.1.7 on 2021-12-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_commander', '0009_auto_20211116_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
