version: "3.9"

services:
  api_server:
    #image: python:3.9.2
    image: django_tut:latest
    build: .

    working_dir: /code
    command: python ./uchi_robochi/manage.py runserver 0.0.0.0:3000
    #user: 1000:1000

    volumes:
      - .:/code
      - ./pip_cache:/root/.cache/pip
    ports:
      - "3000:3000"

    # depends_on:
    #  - db
